#!/bin/bash
lsblk
echo "Kerlek add meg a telepitett rendszert tartalmazo blokk eszkozt!"
echo "Pelda: sda1"
read blkdev
echo "/dev/$blkdev csatolasa /mnt ala!"
mount /dev/$blkdev /mnt
mount --types proc /proc /mnt/proc
mount --bind /run /mnt/run
mount --make-slave /mnt/run
mount --rbind /sys /mnt/sys
mount --rbind /dev /mnt/dev
mount -t tmpfs /tmp /mnt/tmp
echo "source /etc/profile "> /mnt/tmp/chroot_setup.sh
echo "export PS1=\"\[\e[33m\][UHU CHROOT]\[\e[m\] \u@\h \[\e[31m\]-->\[\e[m\] \W \"" >> /mnt/tmp/chroot_setup.sh
chmod +x /mnt/tmp/chroot_setup.sh
chroot /mnt /bin/bash --init-file /tmp/chroot_setup.sh
